name: Add New Activity
description: Request to add a new extracurricular activity or club to the system
title: "[New Activity]: "
labels: ["enhancement", "activity"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping expand our extracurricular activities! Please provide the following information so we can add the new activity to the system.

  - type: input
    id: activity-name
    attributes:
      label: Activity Name
      description: What is the name of the activity or club?
      placeholder: "e.g., Photography Club, Yoga Class, Science Olympiad"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Activity Description
      description: Provide a brief description of what students will do in this activity
      placeholder: "e.g., Learn photography techniques, develop film, and participate in photo contests"
    validations:
      required: true

  - type: dropdown
    id: days
    attributes:
      label: Days of the Week
      description: Select all days when this activity meets
      multiple: true
      options:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
        - Sunday
    validations:
      required: true

  - type: input
    id: start-time
    attributes:
      label: Start Time
      description: When does the activity start? (Use 24-hour format)
      placeholder: "e.g., 15:30 for 3:30 PM, 07:00 for 7:00 AM"
    validations:
      required: true

  - type: input
    id: end-time
    attributes:
      label: End Time
      description: When does the activity end? (Use 24-hour format)
      placeholder: "e.g., 17:00 for 5:00 PM, 08:30 for 8:30 AM"
    validations:
      required: true

  - type: input
    id: max-participants
    attributes:
      label: Maximum Participants
      description: What is the maximum number of students that can participate?
      placeholder: "e.g., 20"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful (e.g., required materials, special room requirements, etc.)
      placeholder: "Add any additional context here..."
    validations:
      required: false

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: The following items should be completed for this task
      options:
        - label: Add the new activity to the database with all provided details
          required: false
        - label: Ensure the activity appears in the activities list on the website
          required: false
        - label: Verify the activity can be filtered by day and time
          required: false
        - label: Test that students can sign up for the activity
          required: false
