blank_issues_enabled: false
contact_links:
  - name: Development Documentation
    url: https://github.com/dez-gilbert/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn how to develop and test the application locally
  - name: GitHub Discussions
    url: https://github.com/dez-gilbert/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss ideas with the community
